# Travis configuration guide for R language:
#   https://docs.travis-ci.com/user/languages/r/
#   https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r

cache: packages

os:
  - linux
  - osx
  
# data.table installation helper
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm &&
    export PATH="/usr/local/opt/llvm/bin:$PATH" &&
    export LDFLAGS="-L/usr/local/opt/llvm/lib" &&
    export CFLAGS="-I/usr/local/opt/llvm/include"; fi

jobs:
  include:
  - r: devel
  - r: release
  - r: 3.5
  - r: 3.4
  - r: 3.3

after_success:
  - Rscript -e 'covr::codecov()'
